########################################################################################################################
#                                                                                                                      #
# .___  ___.  __  .__   __.  __    _______      ___      .___  ___.  _______     ___      .______    __                #
# |   \/   | |  | |  \ |  | |  |  /  _____|    /   \     |   \/   | |   ____|   /   \     |   _  \  |  |               #
# |  \  /  | |  | |   \|  | |  | |  |  __     /  ^  \    |  \  /  | |  |__     /  ^  \    |  |_)  | |  |               #
# |  |\/|  | |  | |  . `  | |  | |  | |_ |   /  /_\  \   |  |\/|  | |   __|   /  /_\  \   |   ___/  |  |               #
# |  |  |  | |  | |  |\   | |  | |  |__| |  /  _____  \  |  |  |  | |  |____ /  _____  \  |  |      |  |               #
# |__|  |__| |__| |__| \__| |__|  \______| /__/     \__\ |__|  |__| |_______/__/     \__\ | _|      |__|               #
########################################################################################################################

mini-game: "Minigame API"